### ISSUE TITLE
Snapshots not being captured.

### ISSUE THREAD

**Issue by bgoggan** [samirans89/percy-csharp-selenium#12]
Updating this issue because running from VS isn't really a requirement I have. I'm running the tests using the dotnet test command and I can see Percy starting but it doesn't take any snapshots. Below is the code I added to my test script and also the logs which are printed. I'm not sure what I'm missing.

percy.Snapshot(DriverHelper.driver, $@"Unauthenticated Home Page {clientName}", null);

[percy] created build #1: https://percy.io/a3ac9fd3/Corestream.Testing.Ui/builds/18568288
[percy] percy has started.
Microsoft (R) Test Execution Command Line Tool Version 16.11.0
Copyright (c) Microsoft Corporation.  All rights reserved.

Starting test execution, please wait...
A total of 1 test files matched the specified pattern.
Info:Broswer used for test: Chrome
Given I login successfully as a registered user to the 'csfriendsfamily' site with email 'qatest1@corestream.com'
Info:I login successfully as a registered user to the 'csfriendsfamily' site with email 'qatest1@corestream.com'
-> done: CommonRePlatformSteps.LoginRegisteredUser("csfriendsfamily", "qatest1@corestrea...") (11.6s)
Then I logout of the client site
Info:I logout of the client site
-> done: CommonRePlatformSteps.LogoutClientSite() (5.7s)
Info:I am in a spot indicating the driver was created or at least the GetDriver is not null

Passed!  - Failed:     0, Passed:     1, Skipped:     0, Total:     1, Duration: 25 s - Corestream.Testing.Ui.dll (netcoreapp3.1)
[percy] stopping percy...
[percy] waiting for 0 snapshots to complete...
[percy] done.
[percy] finalized build #1:

**Comment by bgoggan** [comment]
> Updating this issue because running from VS isn't really a requirement I have. I'm running the tests using the dotnet test command and I can see Percy starting but it doesn't take any snapshots. Below is the code I added to my test script and also the logs which are printed. I'm not sure what I'm missing.
> 
> percy.Snapshot(DriverHelper.driver, $@"Unauthenticated Home Page {clientName}", null);
> 
> [percy] created build #1: https://percy.io/a3ac9fd3/Corestream.Testing.Ui/builds/18568288 [percy] percy has started. Microsoft (R) Test Execution Command Line Tool Version 16.11.0 Copyright (c) Microsoft Corporation. All rights reserved.
> 
> Starting test execution, please wait... A total of 1 test files matched the specified pattern. Info:Broswer used for test: Chrome Given I login successfully as a registered user to the 'csfriendsfamily' site with email '[qatest1@corestream.com](mailto:qatest1@corestream.com)' Info:I login successfully as a registered user to the 'csfriendsfamily' site with email '[qatest1@corestream.com](mailto:qatest1@corestream.com)' -> done: CommonRePlatformSteps.LoginRegisteredUser("csfriendsfamily", "qatest1@corestrea...") (11.6s) Then I logout of the client site Info:I logout of the client site -> done: CommonRePlatformSteps.LogoutClientSite() (5.7s) Info:I am in a spot indicating the driver was created or at least the GetDriver is not null
> 
> Passed! - Failed: 0, Passed: 1, Skipped: 0, Total: 1, Duration: 25 s - Corestream.Testing.Ui.dll (netcoreapp3.1) [percy] stopping percy... [percy] waiting for 0 snapshots to complete... [percy] done. [percy] finalized build #1:

I'll answer my own issue. I had to upgrade to the percy cli instead of percy agent. First uninstalled the percy agent then installed the cli. All is working now.

**Comment by samirans89** [comment]
Thank you @bgoggan. Yes, Percy CLI should be used going forward, as Percy Agent lib has been deprecated since 1+ years ago.
